import './globals.css';
import NavBar from '@/components/NavBar';
import Footer from '../components/Footer';
import { ApolloWrapper } from '@/src/img/context/dataContext';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ApolloWrapper >
          <NavBar/>
            {children}
          <Footer/>
        </ApolloWrapper>
      </body>
    </html>
  )
}
